// Code generated by sqlc. DO NOT EDIT.

import type { Sql } from "postgres";
import type { EmailAddress, UUID } from "$lib/model/types";
import { strToDateTime } from "$lib/model/types";

export type JsonPrimitive = string | number | boolean | null;

export type JsonValue = JsonPrimitive | readonly JsonValue[] | {
    readonly [key: string]: JsonValue | undefined;
};

export interface GetUserArgs {
    id: UUID;
}

interface GetUserRowRaw {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: string;
    invitedAt: string | null;
    loginCount: string;
    quotaBytes: string | null;
    metadata: JsonValue | null;
}

export interface GetUserRow {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: DateTime;
    invitedAt: DateTime | null;
    loginCount: number;
    quotaBytes: number | null;
    metadata: JsonValue | null;
}

export async function getUser(sql: Sql, args: GetUserArgs): Promise<GetUserRow | null> {
    const rows = await sql<GetUserRowRaw[]> `SELECT
  id,
  favorite_team_id,
  email,
  birthday,
  invited_at,
  login_count,
  quota_bytes,
  metadata
FROM users
WHERE id = ${args.id}`;
    const row = rows[0];
    return row === undefined ? null : mapGetUserRow(row);
}

function mapGetUserRow(row: GetUserRowRaw): GetUserRow {
    return {
        ...row,
        birthday: strToDateTime(row.birthday),
        invitedAt: row.invitedAt === null ? null : strToDateTime(row.invitedAt),
        loginCount: Number(row.loginCount),
        quotaBytes: row.quotaBytes === null ? null : Number(row.quotaBytes),
    };
}

export interface ListUsersByFavoriteTeamArgs {
    favoriteTeamId: UUID | null;
}

interface ListUsersByFavoriteTeamRowRaw {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: string;
    invitedAt: string | null;
    loginCount: string;
    quotaBytes: string | null;
    metadata: JsonValue | null;
}

export interface ListUsersByFavoriteTeamRow {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: DateTime;
    invitedAt: DateTime | null;
    loginCount: number;
    quotaBytes: number | null;
    metadata: JsonValue | null;
}

export async function listUsersByFavoriteTeam(sql: Sql, args: ListUsersByFavoriteTeamArgs): Promise<ListUsersByFavoriteTeamRow[]> {
    const rows = await sql<ListUsersByFavoriteTeamRowRaw[]> `SELECT
  id,
  favorite_team_id,
  email,
  birthday,
  invited_at,
  login_count,
  quota_bytes,
  metadata
FROM users
WHERE favorite_team_id = ${args.favoriteTeamId}
ORDER BY birthday`;
    return rows.map(mapListUsersByFavoriteTeamRow);
}

function mapListUsersByFavoriteTeamRow(row: ListUsersByFavoriteTeamRowRaw): ListUsersByFavoriteTeamRow {
    return {
        ...row,
        birthday: strToDateTime(row.birthday),
        invitedAt: row.invitedAt === null ? null : strToDateTime(row.invitedAt),
        loginCount: Number(row.loginCount),
        quotaBytes: row.quotaBytes === null ? null : Number(row.quotaBytes),
    };
}

export interface CreateUserArgs {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: DateTime;
    invitedAt: DateTime | null;
    loginCount: number;
    quotaBytes: number | null;
    metadata: JsonValue | null;
}

interface CreateUserRowRaw {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: string;
    invitedAt: string | null;
    loginCount: string;
    quotaBytes: string | null;
    metadata: JsonValue | null;
}

export interface CreateUserRow {
    id: UUID;
    favoriteTeamId: UUID | null;
    email: EmailAddress;
    birthday: DateTime;
    invitedAt: DateTime | null;
    loginCount: number;
    quotaBytes: number | null;
    metadata: JsonValue | null;
}

export async function createUser(sql: Sql, args: CreateUserArgs): Promise<CreateUserRow | null> {
    const rows = await sql<CreateUserRowRaw[]> `INSERT INTO users (
  id,
  favorite_team_id,
  email,
  birthday,
  invited_at,
  login_count,
  quota_bytes,
  metadata
) VALUES (
  ${args.id}, ${args.favoriteTeamId}, ${args.email}, ${args.birthday}, ${args.invitedAt}, ${args.loginCount}, ${args.quotaBytes}, ${args.metadata === null ? null : sql.json(args.metadata)}
)
RETURNING
  id,
  favorite_team_id,
  email,
  birthday,
  invited_at,
  login_count,
  quota_bytes,
  metadata`;
    const row = rows[0];
    return row === undefined ? null : mapCreateUserRow(row);
}

function mapCreateUserRow(row: CreateUserRowRaw): CreateUserRow {
    return {
        ...row,
        birthday: strToDateTime(row.birthday),
        invitedAt: row.invitedAt === null ? null : strToDateTime(row.invitedAt),
        loginCount: Number(row.loginCount),
        quotaBytes: row.quotaBytes === null ? null : Number(row.quotaBytes),
    };
}

export interface UpdateUserBirthdayArgs {
    id: UUID;
    birthday: DateTime;
}

interface UpdateUserBirthdayRowRaw {
    id: UUID;
    birthday: string;
    invitedAt: string | null;
}

export interface UpdateUserBirthdayRow {
    id: UUID;
    birthday: DateTime;
    invitedAt: DateTime | null;
}

export async function updateUserBirthday(sql: Sql, args: UpdateUserBirthdayArgs): Promise<UpdateUserBirthdayRow | null> {
    const rows = await sql<UpdateUserBirthdayRowRaw[]> `UPDATE users
SET birthday = ${args.birthday}
WHERE id = ${args.id}
RETURNING id, birthday, invited_at`;
    const row = rows[0];
    return row === undefined ? null : mapUpdateUserBirthdayRow(row);
}

function mapUpdateUserBirthdayRow(row: UpdateUserBirthdayRowRaw): UpdateUserBirthdayRow {
    return {
        ...row,
        birthday: strToDateTime(row.birthday),
        invitedAt: row.invitedAt === null ? null : strToDateTime(row.invitedAt),
    };
}

