package ts

import (
	"regexp"
	"strconv"
	"strings"

	"github.com/sqlc-dev/plugin-sdk-go/plugin"

	"github.com/tylergannon/sqlc-gen-typescript/internal/model"
	"github.com/tylergannon/sqlc-gen-typescript/internal/postgres"
)

type File struct {
	Queries  []*Query
	Enums    []EnumDecl
	UsesJSON bool
}

type EnumDecl struct {
	Name string
	Vals []string
}

type Query struct {
	Name      string
	Cmd       string
	Text      string
	ArgsName  string
	Params    []*Field
	RowName   string
	Columns   []*Field
	RawParams []*plugin.Parameter
}

type Field struct {
	Name string
	Type model.TypeRef
}

func Render(file File) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlc. DO NOT EDIT.\n\n")
	b.WriteString("import type { Sql } from \"postgres\";\n\n")

	if file.UsesJSON {
		b.WriteString("export type JsonPrimitive = string | number | boolean | null;\n\n")
		b.WriteString("export type JsonValue = JsonPrimitive | readonly JsonValue[] | {\n")
		b.WriteString("    readonly [key: string]: JsonValue | undefined;\n")
		b.WriteString("};\n\n")
	}
	for _, enumDecl := range file.Enums {
		b.WriteString("export type ")
		b.WriteString(model.PascalCase(enumDecl.Name))
		b.WriteString(" = ")
		for i, val := range enumDecl.Vals {
			if i > 0 {
				b.WriteString(" | ")
			}
			b.WriteString(strconv.Quote(val))
		}
		b.WriteString(";\n\n")
	}
	for _, query := range file.Queries {
		if len(query.Params) > 0 {
			renderInterface(&b, query.ArgsName, query.Params)
		}
		if len(query.Columns) > 0 {
			renderInterface(&b, query.RowName, query.Columns)
		}
		renderFunction(&b, query)
	}
	return b.String()
}

func renderInterface(b *strings.Builder, name string, fields []*Field) {
	b.WriteString("export interface ")
	b.WriteString(name)
	b.WriteString(" {\n")
	for _, field := range fields {
		b.WriteString("    ")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(field.Type.Render())
		b.WriteString(";\n")
	}
	b.WriteString("}\n\n")
}

func renderFunction(b *strings.Builder, query *Query) {
	funcName := model.LowerTitle(query.Name)
	params := "sql: Sql"
	if len(query.Params) > 0 {
		params += ", args: " + query.ArgsName
	}

	switch query.Cmd {
	case ":exec":
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<void> {\n")
		b.WriteString("    await ")
		b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, ""))
		b.WriteString(";\n")
		b.WriteString("}\n\n")
	case ":one":
		returnType := query.RowName
		if returnType == "" {
			returnType = "void"
		}
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<")
		b.WriteString(returnType)
		b.WriteString(" | null> {\n")
		b.WriteString("    const rows = await ")
		b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, returnType+"[]"))
		b.WriteString(";\n")
		b.WriteString("    return rows[0] ?? null;\n")
		b.WriteString("}\n\n")
	case ":many":
		returnType := query.RowName
		if returnType == "" {
			returnType = "void"
		}
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<")
		b.WriteString(returnType)
		b.WriteString("[]> {\n")
		b.WriteString("    return await ")
		b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, returnType+"[]"))
		b.WriteString(";\n")
		b.WriteString("}\n\n")
	}
}

var paramPattern = regexp.MustCompile(`\$(\d+)`)

func buildTaggedTemplate(queryText string, params []*plugin.Parameter, typeArg string) string {
	var b strings.Builder
	b.WriteString("sql")
	if typeArg != "" {
		b.WriteString("<")
		b.WriteString(typeArg)
		b.WriteString(">")
	}
	b.WriteString(" `")

	last := 0
	matches := paramPattern.FindAllStringSubmatchIndex(queryText, -1)
	for _, match := range matches {
		b.WriteString(escapeTemplateText(queryText[last:match[0]]))
		paramNumber, _ := strconv.Atoi(queryText[match[2]:match[3]])
		paramIndex := paramNumber - 1
		expr := "args.arg" + strconv.Itoa(paramIndex)
		if paramIndex >= 0 && paramIndex < len(params) {
			param := params[paramIndex]
			arg := "args." + model.ArgName(paramIndex, param.GetColumn().GetName())
			if postgres.IsScalarJSONColumn(param.GetColumn()) {
				jsonArg := "sql.json(" + arg + ")"
				if param.GetColumn().GetNotNull() {
					expr = jsonArg
				} else {
					expr = arg + " === null ? null : " + jsonArg
				}
			} else {
				expr = arg
			}
		}
		b.WriteString("${")
		b.WriteString(expr)
		b.WriteString("}")
		last = match[1]
	}
	b.WriteString(escapeTemplateText(queryText[last:]))
	b.WriteString("`")
	return b.String()
}

func escapeTemplateText(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}
