package ts

import (
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/sqlc-dev/plugin-sdk-go/plugin"

	"github.com/tylergannon/sqlc-gen-typescript/internal/model"
	"github.com/tylergannon/sqlc-gen-typescript/internal/postgres"
)

type File struct {
	Queries  []*Query
	Enums    []EnumDecl
	UsesJSON bool
}

type EnumDecl struct {
	Name string
	Vals []string
}

type Query struct {
	Name      string
	Cmd       string
	Text      string
	ArgsName  string
	Params    []*Field
	RowName   string
	Columns   []*Field
	RawParams []*plugin.Parameter
}

type Field struct {
	Name      string
	Type      model.TypeRef
	WireType  model.TypeRef
	Converter *ImportRef
}

type ImportRef struct {
	Name       string
	ImportPath string
}

func Render(file File) string {
	var b strings.Builder
	b.WriteString("// Code generated by sqlc. DO NOT EDIT.\n\n")
	b.WriteString("import type { Sql } from \"postgres\";\n")
	renderImports(&b, file)
	b.WriteString("\n")

	if file.UsesJSON {
		b.WriteString("export type JsonPrimitive = string | number | boolean | null;\n\n")
		b.WriteString("export type JsonValue = JsonPrimitive | readonly JsonValue[] | {\n")
		b.WriteString("    readonly [key: string]: JsonValue | undefined;\n")
		b.WriteString("};\n\n")
	}
	for _, enumDecl := range file.Enums {
		b.WriteString("export type ")
		b.WriteString(model.PascalCase(enumDecl.Name))
		b.WriteString(" = ")
		for i, val := range enumDecl.Vals {
			if i > 0 {
				b.WriteString(" | ")
			}
			b.WriteString(strconv.Quote(val))
		}
		b.WriteString(";\n\n")
	}
	for _, query := range file.Queries {
		if len(query.Params) > 0 {
			renderInterface(&b, query.ArgsName, query.Params)
		}
		if len(query.Columns) > 0 {
			if queryHasConverters(query) {
				renderInterfaceWithType(&b, rawRowName(query), query.Columns, true, false)
			}
			renderInterface(&b, query.RowName, query.Columns)
		}
		renderFunction(&b, query)
		if queryHasConverters(query) {
			renderRowMapper(&b, query)
		}
	}
	return b.String()
}

func renderInterface(b *strings.Builder, name string, fields []*Field) {
	renderInterfaceWithType(b, name, fields, false, true)
}

func renderInterfaceWithType(b *strings.Builder, name string, fields []*Field, wire bool, exported bool) {
	if exported {
		b.WriteString("export ")
	}
	b.WriteString("interface ")
	b.WriteString(name)
	b.WriteString(" {\n")
	for _, field := range fields {
		b.WriteString("    ")
		b.WriteString(field.Name)
		b.WriteString(": ")
		if wire && field.Converter != nil {
			b.WriteString(field.WireType.Render())
		} else {
			b.WriteString(field.Type.Render())
		}
		b.WriteString(";\n")
	}
	b.WriteString("}\n\n")
}

func renderFunction(b *strings.Builder, query *Query) {
	funcName := model.LowerTitle(query.Name)
	params := "sql: Sql"
	if len(query.Params) > 0 {
		params += ", args: " + query.ArgsName
	}

	switch query.Cmd {
	case ":exec":
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<void> {\n")
		b.WriteString("    await ")
		b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, ""))
		b.WriteString(";\n")
		b.WriteString("}\n\n")
	case ":one":
		returnType := query.RowName
		if returnType == "" {
			returnType = "void"
		}
		queryType := returnType + "[]"
		if queryHasConverters(query) {
			queryType = rawRowName(query) + "[]"
		}
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<")
		b.WriteString(returnType)
		b.WriteString(" | null> {\n")
		b.WriteString("    const rows = await ")
		b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, queryType))
		b.WriteString(";\n")
		if queryHasConverters(query) {
			b.WriteString("    const row = rows[0];\n")
			b.WriteString("    return row === undefined ? null : ")
			b.WriteString(rowMapperName(query))
			b.WriteString("(row);\n")
		} else {
			b.WriteString("    return rows[0] ?? null;\n")
		}
		b.WriteString("}\n\n")
	case ":many":
		returnType := query.RowName
		if returnType == "" {
			returnType = "void"
		}
		queryType := returnType + "[]"
		if queryHasConverters(query) {
			queryType = rawRowName(query) + "[]"
		}
		b.WriteString("export async function ")
		b.WriteString(funcName)
		b.WriteString("(")
		b.WriteString(params)
		b.WriteString("): Promise<")
		b.WriteString(returnType)
		b.WriteString("[]> {\n")
		if queryHasConverters(query) {
			b.WriteString("    const rows = await ")
			b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, queryType))
			b.WriteString(";\n")
			b.WriteString("    return rows.map(")
			b.WriteString(rowMapperName(query))
			b.WriteString(");\n")
		} else {
			b.WriteString("    return await ")
			b.WriteString(buildTaggedTemplate(query.Text, query.RawParams, queryType))
			b.WriteString(";\n")
		}
		b.WriteString("}\n\n")
	}
}

func renderImports(b *strings.Builder, file File) {
	typeImports := map[string]map[string]bool{}
	valueImports := map[string]map[string]bool{}
	addType := func(typ model.TypeRef) {
		if typ.ImportPath == "" || typ.Name == "" {
			return
		}
		if typeImports[typ.ImportPath] == nil {
			typeImports[typ.ImportPath] = map[string]bool{}
		}
		typeImports[typ.ImportPath][typ.Name] = true
	}
	addValue := func(ref *ImportRef) {
		if ref == nil || ref.ImportPath == "" || ref.Name == "" {
			return
		}
		if valueImports[ref.ImportPath] == nil {
			valueImports[ref.ImportPath] = map[string]bool{}
		}
		valueImports[ref.ImportPath][ref.Name] = true
	}

	for _, query := range file.Queries {
		for _, field := range query.Params {
			addType(field.Type)
			addType(field.WireType)
			addValue(field.Converter)
		}
		for _, field := range query.Columns {
			addType(field.Type)
			addType(field.WireType)
			addValue(field.Converter)
		}
	}

	for _, path := range sortedKeys(typeImports) {
		b.WriteString("import type { ")
		b.WriteString(strings.Join(sortedSymbolKeys(typeImports[path]), ", "))
		b.WriteString(" } from ")
		b.WriteString(strconv.Quote(path))
		b.WriteString(";\n")
	}
	for _, path := range sortedKeys(valueImports) {
		b.WriteString("import { ")
		b.WriteString(strings.Join(sortedSymbolKeys(valueImports[path]), ", "))
		b.WriteString(" } from ")
		b.WriteString(strconv.Quote(path))
		b.WriteString(";\n")
	}
}

func queryHasConverters(query *Query) bool {
	for _, field := range query.Columns {
		if field.Converter != nil {
			return true
		}
	}
	return false
}

func rawRowName(query *Query) string {
	return query.RowName + "Raw"
}

func rowMapperName(query *Query) string {
	return "map" + query.RowName
}

func renderRowMapper(b *strings.Builder, query *Query) {
	b.WriteString("function ")
	b.WriteString(rowMapperName(query))
	b.WriteString("(row: ")
	b.WriteString(rawRowName(query))
	b.WriteString("): ")
	b.WriteString(query.RowName)
	b.WriteString(" {\n")
	b.WriteString("    return {\n")
	b.WriteString("        ...row,\n")
	for _, field := range query.Columns {
		if field.Converter == nil {
			continue
		}
		b.WriteString("        ")
		b.WriteString(field.Name)
		b.WriteString(": ")
		if field.Type.Nullable {
			b.WriteString("row.")
			b.WriteString(field.Name)
			b.WriteString(" === null ? null : ")
		}
		b.WriteString(field.Converter.Name)
		b.WriteString("(row.")
		b.WriteString(field.Name)
		b.WriteString("),\n")
	}
	b.WriteString("    };\n")
	b.WriteString("}\n\n")
}

func sortedKeys(m map[string]map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedSymbolKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

var paramPattern = regexp.MustCompile(`\$(\d+)`)

func buildTaggedTemplate(queryText string, params []*plugin.Parameter, typeArg string) string {
	var b strings.Builder
	b.WriteString("sql")
	if typeArg != "" {
		b.WriteString("<")
		b.WriteString(typeArg)
		b.WriteString(">")
	}
	b.WriteString(" `")

	last := 0
	matches := paramPattern.FindAllStringSubmatchIndex(queryText, -1)
	for _, match := range matches {
		b.WriteString(escapeTemplateText(queryText[last:match[0]]))
		paramNumber, _ := strconv.Atoi(queryText[match[2]:match[3]])
		paramIndex := paramNumber - 1
		expr := "args.arg" + strconv.Itoa(paramIndex)
		if paramIndex >= 0 && paramIndex < len(params) {
			param := params[paramIndex]
			arg := "args." + model.ArgName(paramIndex, param.GetColumn().GetName())
			if postgres.IsScalarJSONColumn(param.GetColumn()) {
				jsonArg := "sql.json(" + arg + ")"
				if param.GetColumn().GetNotNull() {
					expr = jsonArg
				} else {
					expr = arg + " === null ? null : " + jsonArg
				}
			} else {
				expr = arg
			}
		}
		b.WriteString("${")
		b.WriteString(expr)
		b.WriteString("}")
		last = match[1]
	}
	b.WriteString(escapeTemplateText(queryText[last:]))
	b.WriteString("`")
	return b.String()
}

func escapeTemplateText(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}
