// Code generated by sqlc. DO NOT EDIT.

import type { Sql } from "postgres";

export type JsonPrimitive = string | number | boolean | null;

export type JsonValue = JsonPrimitive | readonly JsonValue[] | {
    readonly [key: string]: JsonValue | undefined;
};

export type AuthorStatus = "active" | "inactive" | "pending";

export interface GetAuthorArgs {
    id: number;
}

export interface GetAuthorRow {
    id: number;
    name: string;
    bio: string | null;
    status: AuthorStatus;
    profile: JsonValue;
    notes: JsonValue | null;
}

export async function getAuthor(sql: Sql, args: GetAuthorArgs): Promise<GetAuthorRow | null> {
    const rows = await sql<GetAuthorRow[]> `SELECT id, name, bio, status, profile, notes FROM authors
WHERE id = ${args.id} LIMIT 1`;
    return rows[0] ?? null;
}

export interface ListAuthorsRow {
    id: number;
    name: string;
    bio: string | null;
    status: AuthorStatus;
    profile: JsonValue;
    notes: JsonValue | null;
}

export async function listAuthors(sql: Sql): Promise<ListAuthorsRow[]> {
    return await sql<ListAuthorsRow[]> `SELECT id, name, bio, status, profile, notes FROM authors
ORDER BY name`;
}

export interface CreateAuthorArgs {
    name: string;
    bio: string | null;
    status: AuthorStatus;
    profile: JsonValue;
    notes: JsonValue | null;
}

export interface CreateAuthorRow {
    id: number;
    name: string;
    bio: string | null;
    status: AuthorStatus;
    profile: JsonValue;
    notes: JsonValue | null;
}

export async function createAuthor(sql: Sql, args: CreateAuthorArgs): Promise<CreateAuthorRow | null> {
    const rows = await sql<CreateAuthorRow[]> `INSERT INTO authors (
  name, bio, status, profile, notes
) VALUES (
  ${args.name}, ${args.bio}, ${args.status}, ${sql.json(args.profile)}, ${args.notes === null ? null : sql.json(args.notes)}
)
RETURNING id, name, bio, status, profile, notes`;
    return rows[0] ?? null;
}

export interface ListAuthorsByStatusArgs {
    status: AuthorStatus;
}

export interface ListAuthorsByStatusRow {
    id: number;
    name: string;
    bio: string | null;
    status: AuthorStatus;
    profile: JsonValue;
    notes: JsonValue | null;
}

export async function listAuthorsByStatus(sql: Sql, args: ListAuthorsByStatusArgs): Promise<ListAuthorsByStatusRow[]> {
    return await sql<ListAuthorsByStatusRow[]> `SELECT id, name, bio, status, profile, notes FROM authors
WHERE status = ${args.status}
ORDER BY name`;
}

export interface DeleteAuthorArgs {
    id: number;
}

export async function deleteAuthor(sql: Sql, args: DeleteAuthorArgs): Promise<void> {
    await sql `DELETE FROM authors
WHERE id = ${args.id}`;
}

